name: Unified Dogfooding scans
on:
  schedule:
    # Run Mon-Fri at 2 AM UTC
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: github-ubuntu-latest-s
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          artifactory-reader-role: private-reader    # Override default public-reader
          artifactory-deployer-role: qa-deployer     # Override default public-deployer
          run-shadow-scans: true

      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.java:jdt-package"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.java:jdt-package"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.java:jdt-package"
          shadow2_platform: "SQC-US"
