name: Unified Dogfooding scans
on:
  schedule:
    # Run Mon-Fri at 2 AM UTC
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: github-ubuntu-latest-s
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2026.4.20
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          artifactory-reader-role: private-reader    # Override default public-reader
          artifactory-deployer-role: qa-deployer     # Override default public-deployer
          run-shadow-scans: true

      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.java:jdt-package"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.java:jdt-package"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.java:jdt-package"
          shadow2_platform: "SQC-US"
